spring:
  application:
    name: api-gateway

  config:
    import: optional:configserver:http://localhost:8095

server:
  port: 8094

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO